CREATE TABLE IF NOT EXISTS execution_logs (
  id SERIAL PRIMARY KEY,
  execution_id UUID NOT NULL,
  log_level VARCHAR(10) NOT NULL, -- INFO, WARN, ERROR
  message TEXT NOT NULL,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
